---
# tasks file for roles/ambari-agent
- name: Add ambari repo
  get_url:
    url: 'http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.0.0/ambari.repo'
    dest: '/etc/yum.repos.d/ambari.repo'
    mode: 0644

- name: install ambari-agent
  yum:
      name: ambari-agent
      state: present
      update_cache: yes

- name: Change fqdn for ambari agent
  replace:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "^hostname=.+$"
    replace: "hostname={{ cluster.server.url }}"

- name: Start agent
  command: 'ambari-agent start'
