---
# tasks file for roles/security
- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable selinux
  selinux:
    state: disabled

- name: Reboot hosts
  shell: nohup bash -c "sleep 2s && reboot" &
  async: 0
  poll: 0
  ignore_errors: yes

- name: Wait for reboot
  pause:
    seconds: 10

- name: Wait for hosts coming back ...
  become: no
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    port: 22
    timeout: 300
