- hosts: all
  user: vagrant
  become: true

  roles:
  - { role: common }
  - { role: ansible-transparent-huge-pages }

- hosts: node*
  user: vagrant
  become: true
  
  roles:
  - { role: reboot }

  
- hosts: server
  user: vagrant
  become: true

  roles:
  - ambari_server
  - reboot
  - provision_cluster
  